-- Add BATTERY_STORAGE and THERMO_MODERNIZATION to ProjectType enum
ALTER TYPE "ProjectType" ADD VALUE IF NOT EXISTS 'BATTERY_STORAGE';
ALTER TYPE "ProjectType" ADD VALUE IF NOT EXISTS 'THERMO_MODERNIZATION';
